plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

ext {
    restAssuredVersion = '6.0.0'
    allureVersion = '2.35.3'
    lombokVersion = '1.18.46'
    testngVersion = '7.12.0'
    playwrightVersion = '1.62.0'
    slf4jVersion = '2.0.13'
    logbackVersion = '1.5.6'
    jacksonVersion = '2.17.1'

}

repositories {
    mavenCentral()
}

dependencies {
    // API
    implementation "io.rest-assured:rest-assured:${restAssuredVersion}"

    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    implementation "com.fasterxml.jackson.core:jackson-annotations:${jacksonVersion}"

    // Allure Reports
    testImplementation "io.qameta.allure:allure-rest-assured:${allureVersion}"
    implementation "io.qameta.allure:allure-testng:${allureVersion}"

    // UI
    implementation "com.microsoft.playwright:playwright:${playwrightVersion}"

    // Utils
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    implementation "org.slf4j:slf4j-api:${slf4jVersion}"
    implementation "ch.qos.logback:logback-classic:${logbackVersion}"

    // Testing
    testImplementation "org.testng:testng:${testngVersion}"
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

test {
    useTestNG()

    testLogging {
        events "passed", "skipped", "failed"
        showStandardStreams = true
    }

    systemProperty 'allure.results.directory', 'build/allure-results'
}